# 応用数学
## 第一章：線形代数  
### 行列

- スカラー  
いわゆる数字のこと。向きを持たない
- ベクトル  
大きさと向きを持つ。数字の組み合わせとして示すことができる。

- 行列  
ベクトルを並べたもの。  
ベクトルの変換するために用いる。スカラー倍では「方向」が変化しないので、変化のさせ方にバリエーションを与えるために、行列が利用できる。  
- 直線の式
$$a x_1 + b x_2 = c$$
という式で、直線を表すことができる。  
2直線があれば、交点が1つ定まる。（※コメント：平行でなければ）  
- 連立1次方程式（解説は2元：ただしn元に拡張化）  
2つの関係式（直線）のセット  

- 連立方程式の行列表示  
例として  
$$
\left\{
    \begin{array}{l}
        x_1 + 2 x_2 = 3 \\
        2 x_1 + 5 x_2 = 5
    \end{array}
\right.
$$
は
$$
\left(
    \begin{array}{cc}
        1 & 2 \\
        2 & 5 \\
    \end{array}
\right)
\left(
    \begin{array}{c}
        x_1 \\
        x_2 \\
    \end{array}
\right)
=
\left(
    \begin{array}{c}
        3 \\
        5 \\
    \end{array}
\right)
$$
のように書ける。

- 行列とベクトルの積  
（スカラーの）積と和を組み合わせて、下のように計算される。
$$
\left(
    \begin{array}{cc}
        6 & 4 \\
        3 & 5 \\
    \end{array}
\right)
\left(
    \begin{array}{c}
        1 \\
        2 \\
    \end{array}
\right)
=
\left(
    \begin{array}{c}
        6 \times 1 + 4 \times 2 \\
        3 \times 1 + 5 \times 2 \\
    \end{array}
\right)
$$
※ 非対角成分のおかげでスカラー倍では達成できなかった方向の変化が現れる。  
※ 行列の成分数を（下に）増やしていけば、演算後のベクトルの次元を増やすことができる。  ＿
- 行列と行列の積  
行列同士の積でも、後ろの行列を縦ベクトルを横に並べたものととらえれば、行列とベクトルの積の演算を使って計算することができる。

- 連立方程式の解き方（の例）  
係数をそろえるように一方の式を定数倍することで、一方の文字のみの式を導くことができる。  
「行の定数倍」「ある行に別の行の定数倍を加える」「行を入れ替える」の手続きの組み合わせで解くことができる。  
行列表示で同様の実施を行うことで、「連立方程式を解く」ことと「行列の計算」が対応するのではないかと考えることができる。

- 連立方程式を行列で解く  
2行目の1/2倍は、左から
$$
\left(
    \begin{array}{cc}
        1 & 0 \\
        0 & 1/2 \\
    \end{array}
\right)
$$
を掛けることと同じ。  
１行目から2行目を引くのは、左から
$$
\left(
    \begin{array}{cc}
        1 & -1 \\
        0 & 1 \\
    \end{array}
\right)
$$
を掛けることと同じ。  
式を入れ替えるのは、左から
$$
\left(
    \begin{array}{cc}
        0 & 1 \\
        1 & 0 \\
    \end{array}
\right)
$$
を掛けることと同じ。  
これらの作業は、一般化可能。

- 行列の「逆数」のようなもの  
作用させて行の基本変形を先に計算することで、一つにまとまって行列を得ることができる。  
$$
\left(
    \begin{array}{cc}
        1 & 4 \\
        2 & 6 \\
    \end{array}
\right)
$$
に対して、基本変形部分を計算して得られた
$$
\left(
    \begin{array}{cc}
        -3 & 2 \\
        1 & -1/2 \\
    \end{array}
\right)
$$
は、逆数のように機能する（まるで割り算のように）。  
これを利用することで、「比例の式」のように、連立方程式を解くことができる。

- 単位行列の性質  
後ろからかけても前からかけても、元の行列を変化させない。  
- 単位行列を作る行列⇒逆行列  
$$ A ^{-1} $$
と書く。エーインバースのように読む

- 逆行列の求め方  
（連立方程式を解くときと同じように）行の基本変形を行えば作ることができる。  
拡大行列を使えば、基本変形に対応する行列計算を行わなくても、逆行列が現れる。  
※ 逆行列を求める方法（アルゴリズム）は様々あるが、どんな方法/手順で求めても、得られる逆行列は同じになる。  
※ 分数と同じ記法は、（普通は）しない。

- 逆行列が存在しない場合  
対応する連立方程式を考えたとき、2式が平行になると逆行列を持たない。  
- 幾何的な対応
ad-bc = 0 は平行四辺形の面積 = 0に対応していて、この面積が0の時に逆行列が存在しない。

- 判別式（determinant）  
例えば  
$$  
\left|  
    \begin{array}{cc}  
        1 & 4 \\  
        2 & 6 \\  
    \end{array}  
\right|  
$$  
のように書く。  
- 行列式の特徴  
1. 成分ベクトルに平行成分がある場合は、0。  
2. いずれかの成分ベクトルがλ倍されると行列式もλ倍される。  
3. いずれかの成分ベクトルにベクトルを足した場合、行列式もその部分を変更した行列式を足し合わせたものになる。  
4. 行と列を入れ替えると符号が逆になる。

- 行列式の求め方  
$n \times n$の場合には、分解して$ (n-1) \times (n-1)$に変換する（これを繰り返す）  
※ どのベクトルで分解するのが簡単になるかに着目するとよい。

### 固有値

- 固有値、固有ベクトル  
$$
A \vec{x} = \lambda \vec{x}  
$$  
のとき、λをAの固有値、$\vec{x}$ をAの固有ベクトルという。

- 固有値（$\lambda$）の求め方  
$$  
\left|  
    A - \lambda I  
\right|  = 0
$$  
を解くことで求めることができる。  
※固有値は具体的な値が求められるが、固有ベクトルは○○の定数倍、のような形で求まる。（定数倍はすべて固有ベクトルになるから）

- 固有値分解  
分解をかけることで、似ている部分を強調して理解することができる。  
ある行列Aに対して、その固有値を対角成分に並べた行列を$\Lambda$とし、対応する固有ベクトルを縦ベクトルとして順番通りに並べた行列をVとする。  
ここで、  
$$  
A = V \Lambda V ^{-1}
$$  
が成り立つ。  
※ 例えば、これを用いると行列Aを繰り返しかけあわせる演算が簡単にできる。

- 特異値分解  
固有値分解は、正方形の行列しかできない。長方形に対しては特異値分解をする。  
$$
M \vec{v} = \sigma \vec{u}\\  
M^{T} \vec{u} = \sigma \vec{v}  
$$のような単位ベクトルを得られるとき、Mを
$$  
M = U S V^{T}  
$$  
のように変換でき、これを特異値分解という。  

$M M^{T}$は対称な行列になる。この固有ベクトルは直行する性質がある。

- 特異値分解は何に使う？  
画像の特異値分解をして、部分的に排除しても、おなじような情報に見えてくる。  
画像の特徴を抽出して情報量を減らすことができる。（データが少なくできる）ピントをずらしていくような画像が得られる。

## 演習：線形代数関係

問 1.1.1
$$
\vec{a} + \vec{b} = 
\left( \begin{array}{c} 1 \\ 6 \\ 3 \end{array} \right) + 
\left( \begin{array}{c} 5 \\ 2 \\ 4 \end{array} \right) = 
\left( \begin{array}{c} 6 \\ 8 \\ 7 \end{array} \right)
$$

問 1.1.2
$$
\vec{a} - \vec{b} = 
\left( \begin{array}{c} 1 \\ 6 \\ 3 \end{array} \right) - 
\left( \begin{array}{c} 5 \\ 2 \\ 4 \end{array} \right) = 
\left( \begin{array}{c} -4 \\ 4 \\ -1 \end{array} \right)
$$

問 1.1.3
$$
7\vec{a} = 
7\left( \begin{array}{c} 1 \\ 6 \\ 3 \end{array} \right) =
\left( \begin{array}{c} 7 \\ 42 \\ 21 \end{array} \right)
$$

問 1.1.4  
$$
\begin{eqnarray*}
8\left( \vec{a} + \vec{b} \right) &=& 8\left( \begin{array}{c} 6 \\ 8 \\ 7 \end{array} \right) \\ 
&=&  \left( \begin{array}{c} 48 \\ 64 \\ 56 \end{array} \right)
\end{eqnarray*}
$$
※ 問1の結果を代入した。

問 1.2.1  
$$
A + B = 
\left( \begin{array}{cc} 2 && 1 \\ 5 && 3 \end{array} \right) +
\left( \begin{array}{cc} 1 && 4 \\ 1 && 5 \end{array} \right) = 
\left( \begin{array}{cc} 3 && 5 \\ 6 && 8 \end{array} \right)
$$

問 1.2.2  
$$
A - 3B = 
\left( \begin{array}{cc} 2 && 1 \\ 5 && 3 \end{array} \right) -
3\left( \begin{array}{cc} 1 && 4 \\ 1 && 5 \end{array} \right) = 
\left( \begin{array}{cc} -1 && -11 \\ 2 && -12 \end{array} \right)
$$

問 2.1.1
$$
A\vec{v} = 
\left( \begin{array}{c} 13 \\ 5 \\ 9 \end{array} \right)
$$

問 2.1.2
$$
B\vec{v} = \left( \begin{array}{c} 10 \\ 15 \end{array} \right)
$$

問 2.1.3
$$
AB = \left( \begin{array}{ccc} 10 && 6 && 10 \\
                               25 && 23 && 10 \end{array} \right)
$$

問 2.1.4
$$
B^T = 
\left( \begin{array}{cc} 1 && 0 \\ 0 && 2 \\ 3 && 5 \end{array} \right)
$$

問 2.2.1
$$
AB = \left( \begin{array}{cc} 5 && 7 \\ 7 && 13 \end{array} \right)
$$

問 2.2.2
$$
AB = \left( \begin{array}{cc} -\frac{1}{2} && \frac{1}{2} \\ 2 && -1 \end{array} \right)
$$

問 2.2.3
$$
AB = \left( \begin{array}{cc} -\frac{1}{8} && \frac{3}{8} \\ \frac{3}{8} && -\frac{1}{8} \end{array} \right)
$$

問 2.2.4
$$
AB = \left( \begin{array}{cc} -\frac{1}{4} && \frac{19}{4} \\ \frac{1}{4} && \frac{13}{4} \end{array} \right)
$$

以下、確認（問2.2のみ）

In [14]:
import numpy as np

In [15]:
A = np.array([[2,1],[4,1]])
B = np.array([[1,3],[3,1]])

In [16]:
A.dot(B)

array([[ 5,  7],
       [ 7, 13]])

In [22]:
np.linalg.inv(A)

array([[-0.5,  0.5],
       [ 2. , -1. ]])

In [23]:
np.linalg.inv(B)

array([[-0.125,  0.375],
       [ 0.375, -0.125]])

In [24]:
B.dot(A).dot(np.linalg.inv(B))

array([[-0.25,  4.75],
       [ 0.25,  3.25]])

※ 以下、第6章（対数と乗算除算の関係）は応用数学のいずれの章立てにも馴染まないので、とりあえずここに書く。

問 6.1  
ウ

問 6.2  
イ  

問 6.3  
ウ  

問 7.1  
$$
\vec{a} + \vec{b} = \left(  \begin{array}{c} 3 \\ 7 \\ 7 \end{array} \right)
$$

問 7.2  
$$
\left( \begin{array}{cc} 1 && 4 \\ 2 && 3 \end{array} \right)
\left( \begin{array}{c} 1 \\ 1 \end{array} \right)
= \lambda
\left( \begin{array}{c} 1 \\ 1 \end{array} \right)
$$  
より、
$$
\lambda = 5
$$